// Auto-generated file - DO NOT EDIT
// Generated on 2025-09-04T06:59:40.200Z

window.blogs = [{"title":"基于 Cloudflare Email Routing + Telegram 无限临时地址机器人","date":"2023-10-16 21:33:50","fileName":"2023-10-16-Mail-Bot.md"},{"title":"在node中动态加载代码","date":"2022-04-02 12:50:50","fileName":"2022-04-02-node-dynamicImport.md"},{"title":"ARuler","date":"2017-09-26 01:13:00 ","fileName":"2017-09-26-ARuler.md"},{"title":"LeetCode","date":"2017-02-18 14:48:00 ","fileName":"2017-02-180-My-LeetCode-Project.md"},{"title":"简易扫雷游戏","date":"2017-01-27 22:20:55","fileName":"2017-01-27-MinesWeeping.md"},{"title":"Objective-C 的类变量","date":"2016-12-12 01:23:00","fileName":"2016-12-12-Objective-c-class-property.md"},{"title":"让我们细数 iOS 开发中那些坑爹的变量的默认值","date":"2016-12-12 01:23:00","fileName":"2016-12-16-fxxk-property.md"},{"title":"写 PinterestSegement 中发现的一个问题","date":"2016-12-08 01:23:00","fileName":"2016-12-08-Swift-Pinterst.md"},{"title":"Android - 通用 Viewholder","date":"2016-08-12 01:30:00","fileName":"2016-08-12-Android-quick-viewholder.md"},{"title":"用 Node.js 写简易爬虫","date":"2016-07-31 01:23:00","fileName":"2016-07-31-Nodejs-Spider.md"},{"title":"使用泛型优化 UITableviewCell 的重用","date":"2016-06-10 01:50:10","fileName":"2016-06-10-TableViewWithT.md"},{"title":"超快速为自己的 Github 项目创建 Cocoapods 仓库","date":"2016-05-18 14:50:00 ","fileName":"2016-05-18-Make-Cocoapods.md"},{"title":"RxSwift 笔记","date":"2015-10-29 15:08:27","fileName":"2015-10-29-RxSwift-note.md"},{"title":"Swift笔记","date":"2015-10-19 15:10:10","fileName":"2015-10-19-Swift-note.md"}];

window.exes = [{"name":"github","type":"link","url":"https://github.com/tbxark"},{"name":"twitter","type":"link","url":"https://twitter.com/tbxark"},{"name":"weibo","type":"link","url":"https://weibo.com/tbxark"},{"name":"blogs","type":"command"},{"name":"projects","type":"command"},{"name":"help","type":"command"}];

window.repos = [{"name":"sphere","link":"https://github.com/go-sphere/sphere","description":"Monolithic-first toolkit with codegen for contracts, errors, stubs, and clients"},{"name":"ChatGPT-Telegram-Workers","link":"https://github.com/TBXark/ChatGPT-Telegram-Workers","description":"Easily deploy your Telegram ChatGPT bot on Cloudflare Workers (or Vercel, Docker...)."},{"name":"TKRubberIndicator","link":"https://github.com/TBXark/TKRubberIndicator","description":"A rubber animation pagecontrol"},{"name":"mcp-proxy","link":"https://github.com/TBXark/mcp-proxy","description":"An MCP proxy server that aggregates and serves multiple MCP resource servers through a single HTTP server."},{"name":"mail2telegram","link":"https://github.com/TBXark/mail2telegram","description":"Forward email to telegram with Cloudflare Email Routing"},{"name":"rmtrash","link":"https://github.com/TBXark/rmtrash","description":"rmtrash is a small utility that will move the file to macOS's Trash rather than obliterating the file (as rm does)."},{"name":"github-backup","link":"https://github.com/TBXark/github-backup","description":"A simple tool to backup github repository to gitea or other provider."},{"name":"shell-ask","link":"https://github.com/TBXark/shell-ask","description":"Ask LLM directly from your terminal using a pure bash script"},{"name":"TrieRouter","link":"https://github.com/TBXark/TrieRouter","description":"A simple framework for application routing."},{"name":"telegram-bot-api-types","link":"https://github.com/TBXark/telegram-bot-api-types","description":"This is a project of a type definition file for the Telegram Bot API that generates multilingual automatically."},{"name":"github-status","link":"https://github.com/TBXark/github-status","description":"Generate SVG cards showing your GitHub statistics and programming language distribution"},{"name":"gbvm","link":"https://github.com/TBXark/gbvm","description":"A command line tool to manage Go binaries installed in GOPATH/bin"}];

